Repository 09-MainProject/MyFavIdolFront, pull requests merged in 2025-05, with the labels that each got.

#47 ♻️ refactor: #46 Artist 페이지 리팩토링 & 반응형 UI 작업 완료
  src/components/common/Card/IdolCardList.tsx
  src/pages/artists/Artist.tsx
Labels: refactor: 리팩토링, style: 스타일 변경

#49 Feature/#36 timeline UI
  src/App.tsx
  src/assets/icons/Arrow.tsx
  src/assets/icons/Close.tsx
  src/assets/icons/Comment.tsx
  src/assets/icons/Frame.tsx
  src/assets/icons/Hamburger.tsx
  src/assets/icons/Heart.tsx
  src/assets/icons/inedx.ts
  src/components/CardFrame.tsx
  src/components/common/Card/CommentItem.tsx
  src/components/common/Card/TimelineCard.tsx
  src/components/common/Card/TimelineDetailCard.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Profile/ProfileHeader.tsx
  src/components/layouts/Header/Header.tsx
  src/hooks/useCommentHandlers.tsx
  src/hooks/useDropdownToggle.tsx
  src/hooks/usePostMeta.tsx
  src/mock/comment.ts
  src/pages/timeline/Timeline.tsx
  src/pages/timeline/TimelineDetail.tsx
  src/pages/timeline/TimelineEdit.tsx
  src/pages/timeline/TimelineWrite.tsx
  src/store/useTimelineStore.ts
  src/ts/icon.ts
Labels: feat: 기능 추, refactor: 리팩토링

#50 Feature/#36 timeline
  src/App.tsx
  src/assets/icons/Arrow.tsx
  src/assets/icons/Close.tsx
  src/assets/icons/Comment.tsx
  src/assets/icons/Frame.tsx
  src/assets/icons/Hamburger.tsx
  src/assets/icons/Heart.tsx
  src/assets/icons/inedx.ts
  src/components/CardFrame.tsx
  src/components/common/Card/CommentItem.tsx
  src/components/common/Card/TimelineCard.tsx
  src/components/common/Card/TimelineDetailCard.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Profile/ProfileHeader.tsx
  src/components/layouts/Header/Header.tsx
  src/hooks/useCommentHandlers.tsx
  src/hooks/useDropdownToggle.tsx
  src/hooks/usePostMeta.tsx
  src/mock/comment.ts
  src/pages/timeline/Timeline.tsx
  src/pages/timeline/TimelineDetail.tsx
  src/pages/timeline/TimelineEdit.tsx
  src/pages/timeline/TimelineWrite.tsx
  src/store/useTimelineStore.ts
  src/ts/icon.ts
Labels: feat: 기능 추, refactor: 리팩토링

#52 ♻ refactor: #48 Home 페이지 리팩토링
  src/components/common/Card/IdolCardList.tsx
  src/mocks/idolData.ts
  src/pages/artists/Artist.tsx
  src/pages/home/Home.tsx
Labels: refactor: 리팩토링

#53 Feature/#51 msw login
  .eslintrc.cjs
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/components/common/Card/CommentItem.tsx
  src/components/common/Card/TimelineCard.tsx
  src/components/layouts/Header/Header.tsx
  src/hooks/useCommentHandlers.tsx
  src/main.tsx
  src/mocks/handlers.ts
  src/mocks/handlers/authHandlers.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/loginHandlers.ts
  src/mocks/handlers/logoutHandlers.ts
  src/pages/artists/Artist.tsx
  src/pages/signup/Login.tsx
  src/pages/signup/Signup.tsx
  src/store/authStore.ts
Labels: feat: 기능 추, chore: 기타 작업

#55 Feature/#54 msw profile
  src/components/common/Card/CommentItem.tsx
  src/components/common/Card/TimelineCard.tsx
  src/hooks/useCommentHandlers.tsx
  src/mocks/handlers/authHandlers.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/loginHandlers.ts
  src/mocks/handlers/profileHandlers.ts
  src/store/authStore.ts
Labels: feat: 기능 추

#57 Feature/#56 msw follow
  src/mocks/data/followedIdolsMock.ts
  src/mocks/handlers/followHandlers.ts
  src/mocks/handlers/index.ts
Labels: feat: 기능 추

#61 :sparkles: feat: #60 로그인 시 로그인 상태 유지
  src/components/layouts/Layout.tsx
Labels: feat: 기능 추

#67 :sparkles: feat: API 응답 데이터 type 설정
  src/assets/icons/Arrow.tsx
  src/assets/icons/Close.tsx
  src/assets/icons/Comment.tsx
  src/assets/icons/Frame.tsx
  src/assets/icons/Hamburger.tsx
  src/assets/icons/Heart.tsx
  src/components/layouts/Layout.tsx
  src/mocks/handlers/index.ts
  src/types/auth.ts
  src/types/comment.ts
  src/types/follow.ts
  src/types/icon.ts
  src/types/idolSchedule.ts
  src/types/idols.ts
  src/types/like.ts
  src/types/post.ts
  src/types/userSchedule.ts
Labels: feat: 기능 추

#71 Refactor/#68 timeline detail
  src/components/common/Card/CommentItem.tsx
  src/components/common/Card/TimelineDetailCard.tsx
  src/hooks/useCommentDropdown.tsx
  src/hooks/useCommentHandlers.tsx
  src/hooks/useComments.tsx
  src/mocks/data/comment.ts
  src/pages/timeline/TimelineDetail.tsx
Labels: refactor: 리팩토링

#74 :art: refactor: #73 컴포넌트 폴더 구조 개선 및 책임 분리
  src/components/common/Card/TimelineCard.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Dropdown/Dropdown.tsx
  src/components/layouts/Header/Header.tsx
  src/pages/schedule/IdolDropdownPanel.tsx
  src/pages/timeline/CommentItem.tsx
  src/pages/timeline/Timeline.tsx
  src/pages/timeline/TimelineCard.tsx
  src/pages/timeline/TimelineDetail.tsx
  src/pages/timeline/TimelineDetailCard.tsx
Labels: refactor: 리팩토링

#76 Feature/#75 useimghook
  public/img/defaulImg.jpg
  src/hooks/useImageFallback.tsx
  src/hooks/useImgLazy.tsx
Labels: feat: 기능 추

#79 Feature/#72 artist create
  src/App.tsx
  src/pages/artists/Artist.tsx
  src/pages/artists/CreateArtist.tsx
Labels: feat: 기능 추

#82 Feature/#81 common input
  src/components/common/Input/Input.tsx
  src/pages/signup/Login.tsx
  src/pages/signup/Signup.tsx
  src/pages/timeline/TimelineEdit.tsx
Labels: feat: 기능 추

#85 feature/#83-timeline-comment_delete
  src/hooks/useComments.tsx
  src/pages/timeline/CommentItem.tsx
  src/pages/timeline/TimelineDetail.tsx
Labels: feat: 기능 추

#89 Feature/#88 timelinewrite api
  src/api/img/images.ts
  src/api/timeline/posts.ts
  src/types/post.ts
Labels: feat: 기능 추

#90 Feature/#88 timelinewrite mutation
  src/hooks/useImgLazy.tsx
  src/hooks/usePostImageManager.tsx
  src/hooks/useUploadImageMutation.tsx
Labels: feat: 기능 추

#91 ✨feature: #80 Idol 상세 페이지 및 반응형 UI 구현 및 api 연결
  src/App.tsx
  src/components/common/Card/IdolCardList.tsx
  src/components/common/uploadImageApi.tsx
  src/pages/artists/Artist.tsx
  src/pages/artists/ArtistDetail.tsx
  src/pages/artists/CreateArtist.tsx
  vite.config.ts
Labels: feat: 기능 추

#95 ✨ feat: #93 삭제 기능 구현 및 수정 삭제 UI 구현
  src/components/common/Card/IdolCardList.tsx
  src/pages/artists/ArtistDetail.tsx
Labels: feat: 기능 추

#98 ✨ feat: #96 artist 수정 페이지 구현
  src/App.tsx
  src/pages/artists/ArtistDetail.tsx
  src/pages/artists/EditArtist.tsx
Labels: feat: 기능 추, style: 스타일 변경

#100 🔧 chore: #99 artist 관련 페이지 axios -> api 변경 완료
  src/lib/api.ts
  src/pages/artists/Artist.tsx
  src/pages/artists/ArtistDetail.tsx
  src/pages/artists/CreateArtist.tsx
  src/pages/artists/EditArtist.tsx
Labels: chore: 기타 작업

#105 Feature/#94 timeline mutation
  src/components/common/Profile/ProfileHeader.tsx
  src/hooks/useFetchPosts.tsx
  src/hooks/usePostLikeMutation.tsx
  src/hooks/usePostMeta.tsx
  src/pages/timeline/Timeline.tsx
  src/pages/timeline/TimelineCard.tsx
  src/pages/timeline/TimelineDetail.tsx
Labels: feat: 기능 추

#107 :sparkles: feat: #94 게시판 무한 스크롤 구현
  src/api/timeline/getPosts.ts
  src/hooks/useFetchPosts.tsx
  src/hooks/useInfiniteObserver.tsx
  src/pages/timeline/Timeline.tsx
  src/pages/timeline/TimelineCard.tsx
  src/types/post.ts
Labels: feat: 기능 추

#110 ♻️ refactor: #109 아티스트 상세페이지 useQuery로 idolInfo 상태 적용
  src/pages/artists/ArtistDetail.tsx
Labels: refactor: 리팩토링

#112 ✨ feat: #111 아티스트 페이지 추가 버튼 노출 조건 부여 및 디자인 개선
  src/pages/artists/Artist.tsx
Labels: feat: 기능 추, style: 스타일 변경

#114 🐛 fix: #113 Artist & ArtistDetail 페이지 권한 관련 코드 수정
  src/pages/artists/Artist.tsx
  src/pages/artists/ArtistDetail.tsx
Labels: fix: 버그 수정, refactor: 리팩토링

#115 Feature/#94 timeline skeleton
  src/components/CardFrame.tsx
  src/components/common/Button/IconButton.tsx
  src/components/common/Skeleton/ListCardSkeleton.tsx
  src/components/common/Skeleton/ListSkeleton.tsx
  src/hooks/useImgLazy.tsx
  src/hooks/useLikeState.tsx
  src/pages/timeline/CommentButton.tsx
  src/pages/timeline/LikeButton.tsx
  src/pages/timeline/Timeline.tsx
  src/pages/timeline/TimelineCard.tsx
  src/pages/timeline/TimelineCardImage.tsx
Labels: feat: 기능 추

#116 Feature/#94 timeline
  .eslintrc.json
  src/api/img/getImages.ts
  src/api/timeline/getLikes.ts
  src/api/timeline/getPosts.ts
  src/api/timeline/posts.ts
  src/api/user/getUser.ts
  src/components/CardFrame.tsx
  src/components/common/Button/IconButton.tsx
  src/components/common/Profile/ProfileHeader.tsx
  src/components/common/Skeleton/ListCardSkeleton.tsx
  src/components/common/Skeleton/ListSkeleton.tsx
  src/components/layouts/Header/Header.tsx
  src/components/layouts/Layout.tsx
  src/hooks/useFetchPosts.tsx
  src/hooks/useImgLazy.tsx
  src/hooks/useInfiniteObserver.tsx
  src/hooks/useLikeState.tsx
  src/hooks/usePostMeta.tsx
  src/hooks/useUploadImageMutation.tsx
  src/main.tsx
  src/pages/artists/Artist.tsx
  src/pages/artists/EditArtist.tsx
  src/pages/timeline/CommentButton.tsx
  src/pages/timeline/LikeButton.tsx
  src/pages/timeline/Timeline.tsx
  src/pages/timeline/TimelineCard.tsx
  src/pages/timeline/TimelineCardImage.tsx
  src/pages/timeline/TimelineDetail.tsx
  src/pages/timeline/TimelineWrite.tsx
  src/types/auth.ts
  src/types/like.ts
  src/types/post.ts
Labels: feat: 기능 추, refactor: 리팩토링

#119 Refactor/#118 artist refactor
  .eslintignore
  src/api/idolApi.ts
  src/components/common/Card/IdolCardList.tsx
  src/hooks/useIdolData.tsx
  src/pages/artists/Artist.tsx
  src/pages/artists/ArtistDetail.tsx
  src/store/authStore.ts
Labels: feat: 기능 추, fix: 버그 수정, refactor: 리팩토링, chore: 기타 작업

#121 ✨ feat: #118 home페이지에 아이돌 스케줄 api 연동
  src/pages/home/Home.tsx
Labels: feat: 기능 추

#130 ✨feat: #122 홈페이지에서 아이돌 스케줄 정보 조회 기능 추가
  public/img/swiper1.png
  public/img/swiper2.png
  public/img/swiper3.png
  src/App.tsx
  src/api/idolApi.ts
  src/components/common/Breadcrumb.tsx
  src/components/common/Card/IdolCardList.tsx
  src/components/common/IdolConfirmModal.tsx
  src/components/layouts/Layout.tsx
  src/hooks/useHomeSchedule.tsx
  src/hooks/useIdolData.tsx
  src/pages/artists/Artist.tsx
  src/pages/artists/EditArtist.tsx
  src/pages/home/Home.tsx
  src/pages/schedule/IdolDropdownPanel.tsx
Labels: feat: 기능 추

#131 Feature/#129 schedule
  package-lock.json
  package.json
  src/App.tsx
  src/api/schedules/getSchedules.ts
  src/components/common/Calendar/CalendarTileContent.tsx
  src/components/common/Calendar/CalendarWrapper.tsx
  src/components/common/Card/NotificationInfoCardList.tsx
  src/components/common/Input/Input.tsx
  src/components/layouts/Footer.tsx
  src/components/layouts/Layout.tsx
  src/pages/schedule/Schedule.tsx
  src/pages/schedule/ScheduleDetail.tsx
  src/pages/schedule/components/Card/ScheduleList.tsx
  src/pages/schedule/components/Detail/DetailEditButton.tsx
  src/pages/schedule/components/Detail/DetailInfoItem.tsx
  src/pages/schedule/components/Detail/ScheduleContent.tsx
  src/pages/schedule/components/Detail/ScheduleHeader.tsx
  src/pages/schedule/components/FormSection/ScheduleCreatePage.tsx
  src/pages/schedule/components/FormSection/ScheduleEditorPage.tsx
  src/pages/schedule/components/FormSection/ScheduleForm.tsx
  src/pages/schedule/components/Hooks/useScheduleHandlers.tsx
  src/pages/schedule/components/Hooks/useScheduleMutations.tsx
  src/types/idolSchedule.ts
  src/utils/date.ts
Labels: feat: 기능 추, refactor: 리팩토링

#133 Fix/#132 header login
  src/components/layouts/Header/DesktopNav.tsx
  src/components/layouts/Header/Header.tsx
  src/components/layouts/Header/IdolDropdown.tsx
  src/components/layouts/Header/MobileNav.tsx
  src/components/layouts/Header/UserInfo.tsx
  src/constants/headerMenu.ts
  src/hooks/useMobile.tsx
  src/hooks/useOutsideClick.tsx
  src/pages/schedule/IdolDropdownPanel.tsx
  src/pages/schedule/Schedule.tsx
  src/pages/schedule/ScheduleDetail.tsx
  src/pages/timeline/components/Card/TimelineDetailCard.tsx
  src/pages/timeline/components/hooks/useCommentDropdown.tsx
Labels: fix: 버그 수정, refactor: 리팩토링
