Repository 09-MainProject/MyFavIdolFront, pull requests merged in 2025-04, with the labels that each got.

#3 Feature/#1 header UI
  .eslintrc.json
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icons/Close.tsx
  src/assets/icons/Hamburger.tsx
  src/assets/icons/inedx.ts
  src/components/common/Dropdown.tsx
  src/components/common/IdolDropdownPanel.tsx
  src/components/layouts/Footer.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/Layout.tsx
  src/constants/headerMenu.ts
  src/hooks/useMobile.tsx
  src/index.css
  src/main.tsx
  src/pages/artists/Artist.tsx
  src/pages/home/Home.tsx
  src/pages/schedule/Schedule.tsx
  src/pages/signup/Login.tsx
  src/pages/signup/Signup.tsx
  src/pages/timeline/Timeline.tsx
  src/routes/layouts/Header.tsx
  src/store/idolStore.ts
  tsconfig.app.json
  vite.config.ts
Labels: enhancement

#4 Feature/#1 header
  .eslintrc.json
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icons/Close.tsx
  src/assets/icons/Hamburger.tsx
  src/assets/icons/inedx.ts
  src/components/common/Dropdown.tsx
  src/components/common/IdolDropdownPanel.tsx
  src/components/layouts/Footer.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/Layout.tsx
  src/constants/headerMenu.ts
  src/hooks/useMobile.tsx
  src/index.css
  src/main.tsx
  src/pages/artists/Artist.tsx
  src/pages/home/Home.tsx
  src/pages/schedule/Schedule.tsx
  src/pages/signup/Login.tsx
  src/pages/signup/Signup.tsx
  src/pages/timeline/Timeline.tsx
  src/routes/layouts/Header.tsx
  src/store/idolStore.ts
  tsconfig.app.json
  vite.config.ts
Labels: enhancement

#7 Feature/#2 home Home 페이지 Swiper / Schedule UI 임시 구현 완료
  package-lock.json
  package.json
  src/assets/img/boynextdoor.jpeg
  src/assets/img/ncity.jpeg
  src/assets/img/swiper1.png
  src/assets/img/swiper2.png
  src/assets/img/swiper3.png
  src/components/CardFrame.tsx
  src/pages/home/Home.tsx
Labels: enhancement

#8 :recycle: refactor: 디바운스 함수 useDebouncedFn 제네릭 적용 및 타입 개선
  src/hooks/useDebouncedFn.tsx
  src/hooks/useMobile.tsx
Labels: enhancement

#12 🔁 refactor: #9 useMobile 훅을 사용하여 Home 페이지 반응형 리팩토링
  src/pages/home/Home.tsx
Labels: refactor: 리팩토링, style: 스타일 변경

#15 Feature/#14 schedule calendar
  src/components/common/Calendar/CalendarTileContent.tsx
  src/components/common/Calendar/CalendarWrapper.tsx
  src/components/common/IdolDropdownPanel.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/Layout.tsx
  src/index.css
  src/pages/schedule/Schedule.tsx
  src/store/idolStore.ts
Labels: feat: 기능 추

#16 Feature/#14 schedule notification
  src/assets/icons/Arrow.tsx
  src/assets/icons/inedx.ts
  src/components/common/Calendar/CalendarWrapper.tsx
  src/components/common/Card/NotificationCard.tsx
  src/components/common/Card/NotificationInfoCardList.tsx
  src/components/layouts/Header.tsx
Labels: feat: 기능 추

#17 Feature/#14 schedule UI
  src/components/common/Calendar/CalendarWrapper.tsx
  src/components/common/Card/NotificationCard.tsx
  src/components/layouts/Header.tsx
Labels: style: 스타일 변경

#18 Feature/#14 schedule
  src/assets/icons/Arrow.tsx
  src/assets/icons/inedx.ts
  src/components/common/Calendar/CalendarTileContent.tsx
  src/components/common/Calendar/CalendarWrapper.tsx
  src/components/common/Card/NotificationCard.tsx
  src/components/common/Card/NotificationInfoCardList.tsx
  src/components/common/IdolDropdownPanel.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/Layout.tsx
  src/index.css
  src/pages/schedule/Schedule.tsx
  src/store/idolStore.ts
Labels: feat: 기능 추, style: 스타일 변경

#20 Fix/#19 schedule filter by selected idol
  src/components/common/Calendar/CalendarWrapper.tsx
  src/pages/schedule/Schedule.tsx
Labels: fix: 버그 수정, style: 스타일 변경

#24 🐛 fix: #13 bug 수정
  src/components/common/IdolConfirmModal.tsx
  src/pages/artists/Artist.tsx
  src/pages/schedule/Schedule.tsx
  src/store/idolStore.ts
Labels: fix: 버그 수정

#27 Fix/#25 header dropdown
  src/components/common/IdolDropdownPanel.tsx
  src/components/layouts/Header.tsx
Labels: fix: 버그 수정

#30 Refactor/#29 header refactor
  src/components/common/Dropdown.tsx
  src/components/common/IdolDropdownPanel.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/Header/DesktopNav.tsx
  src/components/layouts/Header/Header.tsx
  src/components/layouts/Header/MobileNav.tsx
  src/components/layouts/Layout.tsx
  src/constants/headerMenu.ts
Labels: refactor: 리팩토링

#32 ✨feat: #28 deploy-dev.yml파일 생성 (cicd 기능 추가)
  .github/workflows/deploy-dev.yml
Labels: feat: 기능 추, ci: CI/CD 설정

#34 :sparkles: feat: #33 /schedule/:id 라우터 및 상세 페이지 UI 추가
  src/App.tsx
  src/components/common/Calendar/CalendarWrapper.tsx
  src/pages/schedule/ScheduleDetail.tsx
Labels: feat: 기능 추

#39 ✨feat: #37 footer UI 구현
  src/components/layouts/Footer.tsx
  src/constants/footerInfo.ts
Labels: feat: 기능 추

#40 Feature/#10 sign up
  src/assets/icons/GoogleIcon.tsx
  src/assets/icons/KakaoIcon.tsx
  src/assets/icons/NaverIcon.tsx
  src/pages/signup/Signup.tsx
Labels: feat: 기능 추

#43 ✨ feat: 화면에 페이지 경로 표시 기능 추가
  src/components/common/Breadcrumb.tsx
  src/components/layouts/Layout.tsx
Labels: feat: 기능 추

#45 Feater/#44 scroll top btn
  src/components/common/ScrollTop.tsx
  src/components/layouts/Layout.tsx
Labels: feat: 기능 추
